package-lock.json, package.json, src/homepage/Homepage.jsx
=> feat: 되는지 확인차 올려봅니다.

src/pages/RecipeDetailPage/RecipeDetailPage.jsx
=> Test:디테일페이지 테스트

package-lock.json, package.json, src/App.js, src/constants/responsive.js, src/hooks/useSliderMenu.js, src/pages/HomePage.jsx, src/pages/Homepage/HomePage.style.css, src/pages/Homepage/component/menuslide/MenuSlide.jsx, src/pages/Homepage/component/randomslide/RandomSlide.jsx, src/pages/Homepage/component/randomslide/RandomSlide.style.css, src/pages/Homepage/homecommon/Slider/HomepageSlider.jsx, src/pages/Homepage/homecommon/Slider/HomepageSlider.style.css, src/pages/Homepage/homecommon/card/SliderCard.jsx, src/pages/Homepage/homecommon/card/SliderCard.style.css
=> add:homepage

src/pages/RecipePage/RecipePage.jsx, src/pages/RecipePage/RecipePage.style.css, src/pages/RecipePage/components/CardComponent.jsx, src/pages/RecipePage/components/CardComponent.style.css
즐겨찾기에 있던 버그 수정 했습니다. 반찬을 필터링 할 수 있게 버튼을 만들었습니다. 카드의 이미지나 이름 설명을 눌럿을때 네비게이트를 이용하여 /recipe/레시피번호 로 이동하게 만들었습니다
=> 즐겨찾기 버그 수정, 필터 기능 추가, 디테일 페이지 이동 (이슈 #14)

src/constants/responsive.js, src/pages/Homepage/HomePage.style.css, src/pages/Homepage/component/randomslide/RandomSlide.jsx, src/pages/Homepage/component/randomslide/RandomSlide.style.css, src/pages/Homepage/homecommon/Slider/HomepageSlider.jsx, src/pages/Homepage/homecommon/Slider/HomepageSlider.style.css, src/pages/Homepage/homecommon/card/SliderCard.jsx, src/pages/Homepage/homecommon/card/SliderCard.style.css
css부분만 조금 손대서 아직 안받고 제가 한 부분만 commit했습니다~ 혹시 문제가 생길 것 같다면 얘기 해주시면 감사하겠습니다~!  homepage부분만 건들였긴했습니당~!
=> add: homepage1 css 

src/pages/Homepage/component/menuslide/MenuSlide.jsx
=> update: 경로 수정

src/pages/RecipeDetailPage/RecipeDetailPage.jsx, src/pages/RecipePage/RecipePage.jsx
=> fix filter logic and bookmark (issue #24)

src/pages/RecipePage/RecipePage.jsx
=> add sort(#issue 24)

src/index.js, src/pages/RecipePage/RecipePage.jsx, src/redux/reducer/bookmarkReducer.js, src/redux/store.js
=> 리듀서를 통해 북마크 기능 완성(이슈 #24)

src/pages/RecipeDetailPage/RecipeDetailPage.jsx
=> homepagecss 수정

src/pages/RecipePage/RecipePage.jsx, src/pages/RecipePage/components/SelectMenu.jsx
=> 음식종류 필터버튼 드롭다운으로 변경(이슈 #35)

src/pages/RecipeDetailPage/RecipeDetailPage.jsx, src/pages/RecipeDetailPage/RecipeDetailPage.style.css
=> feat:레시피디테일 페이지 url복사

src/common/Header/Header.jsx, src/common/Header/Header.style.css, src/pages/RecipeDetailPage/RecipeDetailPage.jsx
=> feat:헤어아이콘수정

src/pages/RecipePage/components/CardComponent.jsx, src/pages/RecipePage/components/CardComponent.style.css
=> feat:레시피페이지 카드컴포넌트 css수정

src/pages/Homepage/component/randomslide/RandomSlide.jsx, src/pages/Homepage/component/randomslide/RandomSlide.style.css
=> fix:homepage css5

src/pages/RecipeDetailPage/RecipeDetailPage.jsx, src/pages/RecipePage/RecipePage.jsx, src/pages/RecipePage/components/CardComponent.jsx
=> 리덕스 북마크 완성 및 비교 로직 변경(이슈 #47)

package-lock.json, src/common/card/SliderCard.jsx, src/common/card/SliderCard.style.css, src/pages/HomePage.jsx, src/pages/Homepage/HomePage.style.css, src/pages/Homepage/component/randomslide/RandomSlide.jsx
=> fix:homepage_css6

src/pages/RecipeDetailPage/RecipeDetailPage.jsx, src/pages/RecipeDetailPage/RecipeDetailPage.style.css, src/pages/RecipeDetailPage/components/StepComponent.jsx, src/pages/RecipeDetailPage/components/StepComponent.style.css
디테일페이지 하단레시피 순서 컴포넌트 추가 + CSS수정
=> feat:디테일페이지 하단 레시피순서추가

src/common/card/SliderCard.jsx
=> fix:homepage_randompage 수정

src/common/card/SliderCard.jsx
=> 슬라이드 카드 리덕스

src/pages/Homepage/HomePage.jsx, src/pages/Homepage/HomePage.style.css
=> feat:homepage 상단 서치영역추가

src/common/Slider/HomepageSlider.style.css, src/common/card/SliderCard.jsx, src/common/card/SliderCard.style.css, src/constants/responsive.js, src/hooks/useRecipeData.js, src/pages/Homepage/component/menuslide/MenuSlide.jsx, src/pages/Homepage/component/randomslide/RandomSlide.jsx, src/pages/Homepage/component/randomslide/RandomSlide.style.css
=> fix:homepage style

src/common/Slider/HomepageSlider.style.css, src/common/card/SliderCard.jsx, src/common/card/SliderCard.style.css, src/pages/Homepage/component/randomslide/RandomSlide.jsx, src/pages/Homepage/component/randomslide/RandomSlide.style.css
=> fix:homepage css

src/common/Slider/HomepageSlider.jsx, src/common/card/NewSliderCard.jsx, src/common/card/NewSliderCard.style.css, src/constants/responsive.js, src/pages/Homepage/component/bookmarkslide/component/BookmarkCardList.jsx, src/pages/Homepage/component/bookmarkslide/component/BookmarkCardList.style.css
=> fix:hamepage slider page

src/pages/RecipePage/RecipePage.jsx, src/pages/RecipePage/RecipePage.style.css
=> 버튼 간격 조절 (#이슈 79)

src/common/card/TopSliderCard.style.css, src/constants/responsiveTop.js, src/pages/Homepage/HomePage.jsx, src/pages/Homepage/HomePage.style.css, src/pages/RecipeDetailPage/RecipeDetailPage.jsx, src/pages/RecipeDetailPage/RecipeDetailPage.style.css, src/pages/RecipeDetailPage/components/StepComponent.jsx, src/pages/RecipeDetailPage/components/StepComponent.style.css
homepage 상단배너수정 
디테일페이지 넘버링
홈페이지 서치영역 모바일css수정
=> feat:homepage top 배너 수정+디테일페이지넘버링

src/common/Slider/HomepageSlider.jsx, src/common/Slider/HomepageSlider.style.css, src/common/card/NewSliderCard.jsx, src/common/card/NewSliderCard.style.css
=> fix:slidercard

src/common/Slider/HomePageTopSlider.jsx, src/common/card/TopSliderCard.jsx, src/common/card/TopSliderCard.style.css, src/constants/responsiveTop.js, src/pages/Homepage/HomePage.style.css
=> fix:homepage top bn 위치수정

src/common/card/TopSliderCard.style.css, src/constants/responsiveTop.js, src/pages/RecipeDetailPage/RecipeDetailPage.jsx, src/pages/RecipeDetailPage/RecipeDetailPage.style.css
=> feat:디테일페이지 찜버튼 변경

src/pages/Homepage/component/bookmarkslide/component/BookmarkNotSliderCard.jsx, src/pages/Homepage/component/bookmarkslide/component/Bookmarkcomponent.Style.css
=> fix:card-bookmark

src/pages/Homepage/component/bookmarkslide/component/BookmarkCardList.jsx, src/pages/Homepage/component/bookmarkslide/component/BookmarkCardList.style.css
=> fix:bookmarkcard fix

src/pages/Homepage/HomePage.jsx, src/pages/Homepage/HomePage.style.css
=> add; plus up button

src/pages/Login/LoginPage.jsx, src/pages/Login/LoginPage.style.css, src/pages/RecipeDetailPage/RecipeDetailPage.jsx, src/pages/RecipeDetailPage/RecipeDetailPage.style.css, src/pages/RecipeDetailPage/components/StepComponent.style.css
=> feat: 디테일페이지지and로그인페이지

src/common/card/TopSliderCard.style.css, src/pages/Homepage/HomePage.style.css, src/pages/Homepage/component/RandomRecipe/RandomRecipe.jsx, src/pages/Homepage/component/RandomRecipe/RandomRecipe.style.css
홈페이지지css 상단배너컴포넌트수정 랜덤배너 타이틀css수정
=> feat:홈페이지지css 상단배너컴포넌트수정

src/common/card/TopSliderCard.jsx, src/pages/Homepage/HomePage.jsx, src/pages/Homepage/component/RandomRecipe/RandomRecipe.style.css, src/pages/Login/LoginPage.style.css
=> feat:랜덤배너수정,업버튼수정

src/pages/Homepage/component/bookmarkslide/BookmarkInfo.style.css, src/pages/Homepage/component/menuslide/MenuSlide.style.css
=> fix:homepage term

src/pages/RecipeDetailPage/RecipeDetailPage.style.css, src/pages/RecipeDetailPage/components/StepComponent.style.css
=> fix:디테일페이지 css수정

src/common/card/NewSliderCard.style.css, src/pages/Homepage/component/bookmarkslide/component/BookmarkCardList.style.css
=> fix:card-term

src/common/card/NewSliderCard.style.css, src/pages/Homepage/component/bookmarkslide/component/BookmarkCardList.style.css, src/pages/RecipeDetailPage/components/StepComponent.style.css
=> fix:term-css

src/common/card/NewSliderCard.jsx, src/common/card/NewSliderCard.style.css, src/pages/Homepage/component/RandomRecipe/RandomRecipe.style.css, src/pages/Homepage/component/menuslide/MenuSlide.jsx, src/pages/Homepage/component/menuslide/MenuSlide.style.css, src/pages/Login/LoginPage.style.css
=> fix:홈페이지 간격조정, 타이틀,css수정

src/pages/Homepage/component/bookmarkslide/BookmarkInfo.jsx, src/pages/Homepage/component/bookmarkslide/BookmarkInfo.style.css, src/pages/Login/LoginPage.style.css
=> fix:로그인배경삽입,홈페이지 하단찜기능 css

src/pages/Homepage/component/menuslide/MenuSlide.style.css
=> menuslide-font

src/pages/RecipePage/components/CardComponent.jsx
=> fix:레시피페이지 아이콘수정

src/pages/Homepage/HomePage.jsx
=> fix:돋보기 모바일

src/pages/Homepage/component/menuslide/MenuSlide.jsx, src/pages/Homepage/component/menuslide/MenuSlide.style.css
=> 모바일 타이틀 수정

src/pages/WishPage/components/WishList.jsx, src/pages/WishPage/components/WishList.style.css
=> fix: wish css
